import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import '../styles/Home.module.css'
import products from '../products.json'
// import "../styles/index.scss"
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h2>
            Gaming HUB
          </h2>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <h1>Welcome to E-commerce</h1>
        </div>

        <div className={styles.grid}>
          {products.map(product => {
            return (
              <div key={product.id} className={styles.card}>
                <div className={styles.dekh}>
                  <img src={product.image} alt={`Preview of ${product.title}`} />
                  <div className={styles.subChild}>
                    <h1>{product.title}</h1>
                    <h2>${product.price}</h2>
                    <p>
                      <button className="snipcart-add-item"
                        data-item-id={product.id}
                        data-item-image={product.image}
                        data-item-name={product.title}
                        data-item-price={product.price}
                      >
                        <h3>Add to Cart</h3>
                      </button>
                    </p>
                  </div>
                </div>

              {/* <div> */}
              <div className={styles.info}>
                <h2>More Details -:</h2>
                <h4>{product.description}</h4>
                </div>
              {/* </div> */}
                

              </div>
            );
          })}
        </div>
      </main>
      <script async src="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.js" />
      <div hidden id="snipcart" data-api-key="ZTZhYmEwMjgtMTVlYy00OTdiLWJjYmEtZmM5OWQzM2I3OWFjNjM4MTczNTMwMTAzMjU2MjM5
" />
    </>
  )
}
